ports:
<<<<<<< HEAD
  - port: 3000
    onOpen: notify
tasks:
  - command: python3 -m http.server 8080
    name: webserver
  - command: >
    name: terminal
=======
  - port: 8080
    onOpen: open-browser
tasks:
  - name: webserver
    command: npx --yes http-server -c-1 # webserver on port 8080 no cache
  - name: shell
    command: >
    
>>>>>>> f17d12555a17f452173adb70cfcf26ee4d6e2e16
